nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ["*"]  # ou ton domaine précis
        allow_headers: ["Content-Type", "Authorization", "Accept", "X-Requested-With", "Origin"]
        allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
        expose_headers: []
        max_age: 3600
    paths:
        "^/api/":
            allow_origin: ["https://canard-muscle.antoninpamart.fr"]
            allow_headers: ["Content-Type", "Authorization", "Accept", "X-Requested-With", "Origin"]
            allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
            max_age: 3600
            allow_credentials: true
