services:
  # Service pour l'application Symfony
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@db:3306/dev
      command: >
        bash -c "php bin/console doctrine:migrations:migrate --no-interaction;
        php -S 0.0.0.0:8000 -t public"


  # Service de base de données MySQL
  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
